version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: infra/docker/worker.Dockerfile
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sil
      POSTGRES_PASSWORD: silpass
      POSTGRES_DB: silcore
    ports:
      - "5432:5432"
